### ISSUE TITLE
problem submitting manager in singularity 

### ISSUE THREAD

**Issue by poquirion** [SIMEXP/psom#120]
from Amal Run on guillimin
```
Traceback (most recent call last):
  File "/usr/local/bin/psom_worker.py", line 119, in main
    first = (int(parsed.worker_id) - 1) * worker_per_node + 1
ValueError: invalid literal for int() with base 10: 'manager'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/psom_worker.py", line 136, in <module>
    main()
  File "/usr/local/bin/psom_worker.py", line 128, in main
    w.start()
  File "/usr/local/bin/psom_worker.py", line 50, in start
    self.fp_out = open(self.std_out, 'w')
FileNotFoundError: [Errno 2] No such file or directory: '/gs/scratch/boukhdha/bascpp_docs/bascpp_source/nki_results/logs/PIPE.out'
```

**Comment by poquirion** [comment]
@pbellec 
Le `logs` est en fait `logssubjectID` dans le code, c'est ce qui fait casser le pipeline. Suis pas sur la meilleur façon de régler ça...

**Comment by poquirion** [comment]
see pull request #121
